### ISSUE TITLE
corrupts menu functionality

### ISSUE THREAD

**Issue by jarrard** [oae/gnome-shell-extensions-sync#1]
corrupts menus from being able to search and display on open specific settings.

This happens for Gno-Menu and Applications Menu, probably most others. I tracked it down to this sync extension corrupting the /.config/dconf/user   file.....

**Comment by oae** [comment]
Hi @jarrard. I couldn't reproduce the problem. Can you provide the steps for me to test?

**Comment by oae** [comment]
I am closing this issue. Please feel free to re-open it.
