### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by fijau** [oae/gnome-shell-extensions-sync#12]
Hi. Thank you for your work on this extension!

I've successfully used it to backup my extensions list to a gist. It seems it is a valid JSON. However, now, on a new Linux installation (same distro) I'm unable to download them. I made sure that the extension has the right gist ID and regenerated the access token. Also confirmed that it has the permission to create gists. I enabled debugging. Now, when I select Download, nothing happens. Log only says "[extensions-sync] [sync] disabled". Any ideas?

**Comment by Ailean** [comment]
Yeah I have the same problem.

I did a backup of my extensions in ubuntu 19.04 and installed 19.10. Then tried to download them and it just doesn't do anything. 

The log says "[extensions-sync] [sync] disabled".

**Comment by oae** [comment]
Hi, Thank you for the feedback. I will try to reproduce this when I have time. It maybe related to an extension that is pre installed with Ubuntu as a system extension.

**Comment by fijau** [comment]
I am using Pop OS 19.10. It has some custom extensions preinstalled.

**Comment by mathewmeconry** [comment]
I can also confirm this issue.
I enabled the debugging mode you mentioned in the Readme but this is the only error I get out

```
JS ERROR: Error: Could not guess unspecified GValue type
activate@resource:///org/gnome/shell/ui/popupMenu.js:182:9                                                  _onButtonReleaseEvent@resource:///org/gnome/shell/ui/popupMenu.js:135:9
```

## OS ##
Fedora 31
Gnome 3.34.3

**Comment by mraxilus** [comment]
I too am  encountering this issue with Pop_OS! 19.10.

**Comment by oae** [comment]
I installed the Pop_OS! 19.10 and tried the extension. It worked with my gist. Can you share your gist with me if it doesn't contain any sensitive data so that I can reproduce the problem?

**Comment by fijau** [comment]
Here's mine: https://pastebin.com/q3H8Skwy (link will expire in a week)

**Comment by AnwarShah** [comment]
Same here. Not uploading the settings

**Comment by mathewmeconry** [comment]
I tried it with an empty new gist but no result...
Here is the last successful sync: https://gist.github.com/mathewmeconry/a531a3e4f6ae521d82823e8314df504b
