### ISSUE TITLE
Set Gist ID and token programmatically ?

### ISSUE THREAD

**Issue by ljak** [oae/gnome-shell-extensions-sync#13]
Could it be possible to set the gist ID and token by command line ? I started to write a script that auto install Gnome Shell Extensions, and if I could set the ID and token in that script, everything could be done during the install.

Thanks! Nice extension by the way.

**Comment by oae** [comment]
You can use `dconf` cli to set the settings.
```sh
dconf write /org/gnome/shell/extensions/sync/gist-id "'my-gist-id'"
dconf write /org/gnome/shell/extensions/sync/gist-token "'my-gist-token'"
```

**Comment by HugoFerrant** [comment]
Just in case anyone like me came here to get this information, the current dconf are now :
```
/org/gnome/shell/extensions/extensions-sync/github-gist-id
/org/gnome/shell/extensions/extensions-sync/github-user-token
/org/gnome/shell/extensions/extensions-sync/gitlab-snippet-id   
/org/gnome/shell/extensions/extensions-sync/gitlab-user-token   
```
