### ISSUE TITLE
[UX] Make upload and download icons look less similar.

### ISSUE THREAD

**Issue by RubenSibon** [oae/gnome-shell-extensions-sync#16]
**UX problem**

From a distance and on hi-res displays it is difficult to see what way that the arrow in the icons for Upload and Download.

**Possible solution**

Make the arrow heads bigger of more clear. 

I looked for a suitable GTK icon but could not find one.

**Comment by oae** [comment]
![image](https://user-images.githubusercontent.com/1043714/91187891-57a68f00-e6f9-11ea-8ae0-9e3c47f991f8.png)

What do you think about these? I made arrowheads bigger.

**Comment by RubenSibon** [comment]
That looks better to me!
