### ISSUE TITLE
An error occured while downloading settings ...

### ISSUE THREAD

**Issue by JoTrab** [oae/gnome-shell-extensions-sync#17]
I manage to upload to my github gist, but downloading seems impossible. I get a notification that: ''An error occured while downloading settings ...''   and neither Tweaks, key-bindings, nor extensions are downloaded. 
Best regards, jo
Gnome version 3.36.3 on ubuntu 20.04.

**Comment by oae** [comment]
Can you check the logs with `journalctl  -f /usr/bin/gnome-shell` while trying to download? What does it say?

**Comment by JoTrab** [comment]
It says 

> Too many arguments to method Gio.OutputStream.write: expected 2, got 

and  
> gnome-shell[2654]: [extensions-sync] [api] error occured during download SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data

**Comment by oae** [comment]
Can you share your gist if it is ok for you? There seems to a problem with json in gist

**Comment by oae** [comment]
In your gist file, there should be `extensions`, `keybindings`, and `tweaks` files. If you have files other than these three, you should delete it as a workaround for now. I have fixed it and will upload a new version soon.

**Comment by JoTrab** [comment]
Thanks, it works now. I thought I had already deleted the dummy file needed to create a gist but it was still there. I made sure to delete it and it works fine. Thanks again for the quick answer and the great extensions.
