### ISSUE TITLE
Sync to file

### ISSUE THREAD

**Issue by laurinneff** [oae/gnome-shell-extensions-sync#19]
Since GNOME has the feature to connect cloud accounts, I thought this extension probably supports those. Sadly not. Would be cool if you could implement syncing to a file, so I could use my Nextcloud to sync my extensions

**Comment by oae** [comment]
I have added local file sync support in [latest release](https://github.com/oae/gnome-shell-extensions-sync/releases/tag/v10). You can download it from the releases page or wait for EGO to update it to the latest version.

![image](https://user-images.githubusercontent.com/1043714/97648136-0ef6b380-1a65-11eb-8f70-90dba93716d8.png)
