### ISSUE TITLE
[Feature] Hide Icon

### ISSUE THREAD

**Issue by PHLAK** [oae/gnome-shell-extensions-sync#2]
I don't want an icon cluttering my system tray. It would be nice to have an option to disable the icon.

![image](https://user-images.githubusercontent.com/53531/56751769-acb84680-673b-11e9-916c-29b95fee9afd.png)

**Comment by mrbmi513** [comment]
I second this. Love the concept, hate having another icon cluttering my tray. Maybe just move the upload and download options to the settings menu instead?

**Comment by oae** [comment]
Thanks for the feedback. I will look into this.

**Comment by oae** [comment]
I add hiding icon support if I implement #3
