### ISSUE TITLE
Synchronise also /org/gnome/shell/keybindings

### ISSUE THREAD

**Issue by kheraud** [oae/gnome-shell-extensions-sync#21]
`/org/gnome/shell/keybindings` is not part of the keybindings synced by the extension.

This entry contains keys which are part of the "global gnome" keybindings :

```
focus-active-notification=@as []
open-application-menu=@as []
switch-to-application-1=@as []
switch-to-application-2=@as []
switch-to-application-3=@as []
switch-to-application-4=@as []
switch-to-application-5=@as []
switch-to-application-6=@as []
switch-to-application-7=@as []
switch-to-application-8=@as []
switch-to-application-9=@as []
toggle-application-view=['<Super>d']
toggle-message-tray=@as []
toggle-overview=@as []
```

For example here, I disable the native `Super+?` for `switch-to-application-?` and I add `Super+D` for application view.

**Comment by oae** [comment]
I must have missed it. I will add it as soon as I have access to my gnome environment

**Comment by oae** [comment]
I have added `/org/gnome/shell/keybindings/` in version [v12](https://github.com/oae/gnome-shell-extensions-sync/releases/tag/v12). It might take several days to be updated in extensions.gnome.org.

**Comment by kheraud** [comment]
Great work
