### ISSUE TITLE
Update for Gnome 40

### ISSUE THREAD

**Issue by noirbizarre** [oae/gnome-shell-extensions-sync#25]
Hi 👋🏼 !

Can you update and publish a version of this great extension for Gnome 40 ?

**Comment by oae** [comment]
Hi,

I am planning to fix it sometime next week.

**Comment by noirbizarre** [comment]
Great news !!! 🎉 🎊 

I'll be glad to help testing if needed.
By the way, you are so fast to answer, kudo !!!!

**Comment by oae** [comment]
@noirbizarre I have released the v13 version and uploaded it to EGO. It may take few days for reviews.

**Comment by noirbizarre** [comment]
It's already available (this is a good surprise EOG is usualy slow to validate extension).
Insalled and works fine 👌🏼 

Thanks !
