### ISSUE TITLE
Settings for the extension can't be displayed

### ISSUE THREAD

**Issue by paddylandau** [oae/gnome-shell-extensions-sync#27]
On trying to open the settings for this extension, I receive the following message:

> Something's gone wrong. We're very sorry, but there's been a problem: the settings for this extension can't be displayed. We recommend that you report the issue to the extension authors.

I'm using Ubuntu 20.04 with Gnome 3.36.8.

The error message includes the following technical details.

```
TypeError: providerSelectionContainer.append is not a function

Stack trace:
  _init@/home/paddy/.local/share/gnome-shell/extensions/extensions-sync@elhan.io/prefs.js:102:40
  createNotebook@/home/paddy/.local/share/gnome-shell/extensions/extensions-sync@elhan.io/prefs.js:1514:35
  _init@/home/paddy/.local/share/gnome-shell/extensions/extensions-sync@elhan.io/prefs.js:1507:18
  buildPrefsWidget@/home/paddy/.local/share/gnome-shell/extensions/extensions-sync@elhan.io/prefs.js:1522:36
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

I tried uninstalling the extension, restarting the computer and reinstalling the extension, but that didn't help.

I have no idea how to understand, diagnose or fix this problem.

**Comment by oae** [comment]
Gnome 40 forced extensions to use gtk4 for preferences so I rewrote the code for settings GUI. You can install the [v12](https://github.com/oae/gnome-shell-extensions-sync/releases/tag/v12) version. Remove the currently installed extension. After that download the `extensions-sync@elhan.io.zip` from the releases page and extract its content into `$HOME/.local/share/gnome-shell/extensions/extensions-sync@elhan.io`.

**Comment by paddylandau** [comment]
> I have removed the 3.36 from the latest version of the extension now. Can you remove and install it again from extensions.gnome.org? It should work now

Thank you! I had to restart the computer before reinstalling, but then it worked.
