### ISSUE TITLE
Alt+Tab, Super+Tab

### ISSUE THREAD

**Issue by kamilizmer** [oae/gnome-shell-extensions-sync#4]
After installing and sync extensions the option of alt+tab to switching app windows was disabled. If I disabled that extension and reload of alt+f2 -> R then everything works again. Restart of the system with switched on that extension doesn't work :(

**Comment by mrbmi513** [comment]
Alt+Tab and Super+Tab still work for me. Ubuntu 18.04.2 LTS / GNOME 3.28.2

**Comment by kamilizmer** [comment]
Here is Ubuntu 19.04 / Gnome 3.32 ;)

**Comment by henrik-wittenberg** [comment]
Standard Alt+Tab and Super+Tab works for me, but not if I want to use the extension "Coverflow Atl-Tab".

I have to disable "Extension Sync" if I want to use "Coverflow Atl-Tab" instead of the standard Gnome Alt-Tab.

Manjaro
GNOME Shell 3.34.1
