### ISSUE TITLE
Clarify Github Gists explanation

### ISSUE THREAD

**Issue by benblasco** [oae/gnome-shell-extensions-sync#40]
Thank you for creating this great extension.  I propose we clarify the explanation of using Github gists to make it clear that the Gist ID is (for example) "f545156c0083f7eaefa44ab69df4ec37" rather than "https://gist.github.com/username/f545156c0083f7eaefa44ab69df4ec37".  Happy to do this via a PR if you are comfortable with a stranger's contributions!  I can even update the explanation with more detailed screenshots if you like.

**Comment by oae** [comment]
Added some guides on the readme. Thanks for the feedback
