### ISSUE TITLE
Missing settings of some extensions

### ISSUE THREAD

**Issue by G-dH** [oae/gnome-shell-extensions-sync#41]
Hi,
very useful extension, but some extensions are not supported. I'd say the problem is that extensions with different name in uuid and the gsettings schema and also gsettings subdirectories are ignored. For example `Custom Hot Corners (- Extended)` have all settings in subdirectories, `AATWS - Advanced Alt-Tab Window Switcher` has different uuid and schema name, but the information is available in its `metadata.json` file.

**Comment by oae** [comment]
HI, I checked the extensions you mentioned. `<schema>` tags are missing `path` property. It should be like this;

```xml
<schema path="/org/gnome/shell/extensions/extensions-sync/" id="org.gnome.shell.extensions.extensions-sync">
```

**Comment by G-dH** [comment]
Thanks! You're right, I missed that. I fixed it partially, Custom Hot Corners extensions create dynamically multiple paths derived from a single schema...

**Comment by oae** [comment]
There needs to be a path for this extension to work. If the generated schema paths are under the same path (e.g. /org/gnome/shell/extensions/extensions-sync/dyn1, /org/gnome/shell/extensions/extensions-sync/dyn2) then they will be synced.

**Comment by G-dH** [comment]
I finally got to this again and solved it. `relocatable` schema (without the path) needs to be addressed like this:

    <schema path='/org/gnome/shell/extensions/custom-hot-corners-extended/' id='org.gnome.shell.extensions.custom-hot-corners-extended'>
        <child  name='corner' schema='org.gnome.shell.extensions.custom-hot-corners-extended.corner'/>
    </schema>

Now sync work flawlessly. Thanks!
