### ISSUE TITLE
console is not defined

### ISSUE THREAD

**Issue by trolliama** [oae/gnome-shell-extensions-sync#42]
HI, I am using Pop OS 21.10 and I just faced this "console is not defined" error

I don't know if it's an issue or not but it just appeared from nothing because I was using the extension before without this error

Here is the error:
![image](https://user-images.githubusercontent.com/21108976/147889180-591e2c28-437f-4597-957f-dcfb2735af93.png)

**Comment by TavoAdr** [comment]
It's been happening to me for a long time too, but since I don't need to use it much, I never try to find out what it is. (I use Pop Os to, latest version)

**Comment by trolliama** [comment]
I actually use this a little bit and right now I am having this error. I formatted my notebook (Pop os 20.04) and installed it again and was working as expected but now it just broke out of nowhere

**Comment by oae** [comment]
I tried to reproduce this on Pop OS 21.10 but I didn't get any error. Maybe some other extension is causing this problem?

**Comment by TavoAdr** [comment]
Idk why, but that's work now. Pop!_OS 21.10 after extension update
