### ISSUE TITLE
Support any git repo as a backend system

### ISSUE THREAD

**Issue by stdedos** [oae/gnome-shell-extensions-sync#47]
Hello there!

Would it be possible/wanted to additionally support using a plain git repository (stored on Github, accessed via ssh, etc etc) to do the syncing, in addition to using snippets?

**Comment by oae** [comment]
You can use the Local provider and point it to a file in a repository. In addition to this, it is also possible to use dbus commands to automate the process.

```sh
busctl --user call org.gnome.Shell /io/elhan/ExtensionsSync io.elhan.ExtensionsSync save # uploads to server
busctl --user call org.gnome.Shell /io/elhan/ExtensionsSync io.elhan.ExtensionsSync read # downloads to pc
```

![image](https://user-images.githubusercontent.com/1043714/167392294-097e7b3f-7929-4a97-8db3-c099b59da14e.png)

**Comment by oae** [comment]
I am closing this since there is no answer. Feel free to open it again.
