### ISSUE TITLE
not working on 3.30 on Debian Buster

### ISSUE THREAD

**Issue by HankB** [oae/gnome-shell-extensions-sync#5]
On one PC it installs and once configured does something but I don't see anything in the gist. I did not see any way to trigger upload/download.

I enabled debugging and do not see any error/warning indications.
I've installed it on another PC (Same Debian version and desktop) and once configured it reported "error" on the chrome extension pages.
I tried to turn on debugging on the second PC and get 

```
root@olive05:~# busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'window.extensionsSync.debug = true;'
Failed to set address: No such file or directory
root@olive05:~# journalctl /usr/bin/gnome-shell -o cat | grep "\[extensions-sync\]"
root@olive05:~# 
```
Not sure where to go from here.

**Comment by oae** [comment]
See #6
