### ISSUE TITLE
Save dconf-editor settings too

### ISSUE THREAD

**Issue by sanjarcode** [oae/gnome-shell-extensions-sync#50]
In addition to gnome-extensions, tweaks and keybindings, I use `dconf-editor` to set very specific desktop preferences like dock settings (delay, height, transparency for example) etc. Can we save that too?

**Comment by oae** [comment]
Hi,

The extension is backing up and restoring keys under the following dconf paths. Which path are you referring to for dock settings?

```
  '/org/gnome/mutter/keybindings/',
  '/org/gnome/mutter/wayland/keybindings/',
  '/org/gnome/shell/keybindings/',
  '/org/gnome/desktop/wm/keybindings/',
  '/org/gnome/settings-daemon/plugins/media-keys/',
  '/org/gnome/desktop/background/',
  '/org/gnome/desktop/calendar/',
  '/org/gnome/desktop/input-sources/',
  '/org/gnome/desktop/interface/',
  '/org/gnome/desktop/peripherals/',
  '/org/gnome/desktop/screensaver/',
  '/org/gnome/desktop/sound/',
  '/org/gnome/desktop/wm/preferences/',
  '/org/gnome/mutter/',
  '/org/gnome/settings-daemon/plugins/xsettings/',
```

**Comment by sanjarcode** [comment]
Using `dconf-editor` creates a file.
Path: `~/.config/user` (yes, it's literally named "user")
[Contents - adding as TXT but the file has no extension](https://github.com/oae/gnome-shell-extensions-sync/files/9386109/user.txt)

**Comment by sanjarcode** [comment]
This could really be an awesome feature, because Windows saves every minute detail, afaik. Your extension is the first step in that direction, for Gnome.

**Comment by oae** [comment]
I believe that file contains all dconf settings. I don't plan to add file syncnoization. But if you have specific dconf paths in your mind, i can add them. Which dock do refer to? dash-to-dock extension?
