### ISSUE TITLE
Support for GNOME 44

### ISSUE THREAD

**Issue by FlexibleToast** [oae/gnome-shell-extensions-sync#59]
Please update to support GNOME 44.

**Comment by hrqmonteiro** [comment]
It's working fine, i opened a [PR](https://github.com/oae/gnome-shell-extensions-sync/pull/61) adding the 44 version to metadata

![Screenshot from 2023-05-16 14-32-34](https://github.com/oae/gnome-shell-extensions-sync/assets/17055027/b4b44fba-d2ea-464a-97e0-eb332e14912e)

**Comment by nPrevail** [comment]
> i opened a [PR](https://github.com/oae/gnome-shell-extensions-sync/pull/61) adding the 44 version to metadata

Is it possible to add "any version" to the metadata, for future Gnome releases?

**Comment by hrqmonteiro** [comment]
> > i opened a [PR](https://github.com/oae/gnome-shell-extensions-sync/pull/61) adding the 44 version to metadata
> 
> Is it possible to add "any version" to the metadata, for future Gnome releases?

No, it receives an array of numbers, so it have to exactly contain which versions it supports. And sometimes it is not just a matter of inserting the number on it, sometimes the shell changes some APIs and the extension breaks in a new version, so changes are necessary.

**Comment by FlexibleToast** [comment]
I'm glad to hear it works and there is a PR for it. I didn't dig into trying to get it to work. Instead I actually dug into Chezmoi and now I track parts of a dconf dump that do the things I wanted extension sync mostly for and it tracks other configurations. I'll probably end up using both when the PR gets accepted because it's just easier.

**Comment by benblasco** [comment]
FWIW extensions.gnome.org now allows you to disable version validation:

![image](https://github.com/oae/gnome-shell-extensions-sync/assets/42140583/8fa37bd4-4145-4003-bc5b-6c0b896369b4)

**Comment by oae** [comment]
I have released the new version for the 44
