### ISSUE TITLE
Remove Array.prototype.diff prototype augmentation

### ISSUE THREAD

**Issue by GeeWee** [oae/gnome-shell-extensions-sync#7]
In `sync.js` we're augmenting array with Array.prototype.diff
This can break other extensions looping over arrays (see e.g. https://github.com/gTile/gTile/issues/22#issuecomment-493733490)

I think it would be best to remove the prototype augmentation, it's widely considered a bad idea in environments where code have to share a runtime.

**Comment by oae** [comment]
thank you for the feedback. I have removed it and will release it in the next version

**Comment by GeeWee** [comment]
Awesome! Thanks!
